### ISSUE TITLE
项目添加配置和生成新的数据库后，运行报错

### ISSUE THREAD

**Issue by 52lemon** [alvan/luokr.com#13]
`
[E 190830 17:25:10 web:1670] Uncaught exception GET / (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8001', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "E:\FanProjects\luokr.com\app\ctrls\posts.py", line 38, in get
        (stime, pager['qnty'], (pager['page']-1)*pager['qnty'], ))
      File "E:\FanProjects\luokr.com\lib\datum.py", line 31, in result
        cur.execute(*args, **kwargs)
    OperationalError: no such table: posts
[E 190830 17:25:10 web:1114] Uncaught exception in write_error
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\web.py", line 1112, in send_error
        self.write_error(status_code, **kwargs)
      File "E:\FanProjects\luokr.com\app\ctrls\basic.py", line 50, in write_error
        self.flash(0, {'sta': status_code})
      File "E:\FanProjects\luokr.com\app\ctrls\basic.py", line 196, in flash
        self.render('flash.html', resp = resp)
      File "C:\Python27\lib\site-packages\tornado\web.py", line 766, in render
        html = self.render_string(template_name, **kwargs)
      File "C:\Python27\lib\site-packages\tornado\web.py", line 907, in render_string
        return t.generate(**namespace)
      File "C:\Python27\lib\site-packages\tornado\template.py", line 346, in generate
        return execute()
      File "flash_html.generated.py", line 13, in _tt_execute
        _tt_tmp = handler.get_runtime_conf('title')  # flash.html:3 (via _base.html:5)
      File "E:\FanProjects\luokr.com\app\ctrls\basic.py", line 55, in get_runtime_conf
        return self.datum('confs').obtain(name)
      File "E:\FanProjects\luokr.com\app\datum\confs.py", line 21, in obtain
        ret = self.record('select conf_vals from confs where conf_name = ?', (name, ))
      File "E:\FanProjects\luokr.com\lib\datum.py", line 38, in record
        cur.execute(*args, **kwargs)
    OperationalError: no such table: confs
[E 190830 17:25:10 web:2162] 500 GET / (127.0.0.1) 36.00ms
`

**Comment by alvan** [comment]
You may need to run `app/tools/dbase.py` to init tables.
Please also check the README file for more details.
